In [2]:
#installing required libraries:
import numpy as np
import pandas as pd
import matplotlib as plot

In [4]:
#Reading data:
df = pd.read_csv('Raw_data/Crash_Report.csv')

In [6]:
#Raw data:
df.shape

df.info()

df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208968 entries, 0 to 208967
Data columns (total 23 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Report Number           208968 non-null  object
 1   Local Case Number       208968 non-null  object
 2   Agency Name             208968 non-null  object
 3   ACRS Report Type        208968 non-null  object
 4   Crash Date/Time         208968 non-null  object
 5   Route Type              188510 non-null  object
 6   Road Name               184977 non-null  object
 7   Cross-Street Name       169632 non-null  object
 8   Collision Type          208383 non-null  object
 9   Weather                 195612 non-null  object
 10  Surface Condition       185185 non-null  object
 11  Light                   207523 non-null  object
 12  Traffic Control         180061 non-null  object
 13  Driver Substance Abuse  177648 non-null  object
 14  Driver At Fault         208968 non-null  object
 15  Injury Severity         206456 non-null  object
 16  Driver Distracted By    206265 non-null  object
 17  Drivers License State   194819 non-null  object
 18  Vehicle Body Type       205792 non-null  object
 19  Speed Limit             208968 non-null  int64
 20  Vehicle Year            208968 non-null  int64
 21  Vehicle Make            207894 non-null  object
 22  Vehicle Model           207852 non-null  object
dtypes: int64(2), object(21)
memory usage: 36.7+ MB

,Report Number,Local Case Number,Agency Name,ACRS Report Type,Crash Date/Time,Route Type,Road Name,Cross-Street Name,Collision Type,Weather,...,Driver Substance Abuse,Driver At Fault,Injury Severity,Driver Distracted By,Drivers License State,Vehicle Body Type,Speed Limit,Vehicle Year,Vehicle Make,Vehicle Model
0,MCP3126006X,250037402,MONTGOMERY,Injury Crash,08/21/2025 05:21:00 PM,Maryland (State) Route,NaN,NaN,Front to Rear,Clear,...,"Not Suspect of Alcohol Use, Not Suspect of Dru...",Yes,No Apparent Injury,"Other Action (looking away from task, etc.)",MD,Passenger Car,40,2013,KIA,SOUL
1,MCP2349001B,250037516,MONTGOMERY,Property Damage Crash,08/22/2025 10:44:00 AM,Interstate (State),EISENHOWER MEMORIAL HWY,NaN,Single Vehicle,Clear,...,"Unknown, Unknown",No,NaN,NaN,NaN,NaN,55,0,NaN,NaN
2,MCP296500BC,250033157,MONTGOMERY,Property Damage Crash,07/25/2025 11:55:00 AM,Bicycle Route,NaN,NEW HAMPSHIRE AVE (SB/L) NORBECK RD (WB/L) SPE...,"Sideswipe, Same Direction",Clear,...,"Not Suspect of Alcohol Use, Not Suspect of Dru...",No,No Apparent Injury,Not Distracted,CO,Passenger Car,40,2023,LEXUS,RX
3,MCP2159003K,250037509,MONTGOMERY,Property Damage Crash,08/22/2025 10:36:00 AM,Maryland (State) Route,NaN,NaN,Front to Rear,Clear,...,"Not Suspect of Alcohol Use, Not Suspect of Dru...",Yes,No Apparent Injury,"Manually Operating (dialing, playing game, etc.)",MD,Van - Passenger (&lt;9 Seats),30,2003,TOYOTA,SIENNA
4,MCP312900D6,250034573,MONTGOMERY,Property Damage Crash,08-03-25 14:10,NaN,NaN,NaN,Rear To Side,Clear,...,"Unknown, Unknown",No,NaN,Unknown,NaN,Sport Utility Vehicle,0,2023,SUBARU,IMPREZA

In [7]:
#Checking for NULL values:
missing = df.isnull().sum()
missing_pct = (missing / len(df)) * 100

pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percentage": missing_pct
}).head(15)

                        Missing_Count  Missing_Percentage
Report Number                       0            0.000000
Local Case Number                   0            0.000000
Agency Name                         0            0.000000
ACRS Report Type                    0            0.000000
Crash Date/Time                     0            0.000000
Route Type                      20458            9.790016
Road Name                       23991           11.480705
Cross-Street Name               39336           18.823935
Collision Type                    585            0.279947
Weather                         13356            6.391409
Surface Condition               23783           11.381168
Light                            1445            0.691493
Traffic Control                 28907           13.833218
Driver Substance Abuse          31320           14.987941
Driver At Fault                     0            0.000000

In [8]:
#Handling NULL values:
cat_cols = df.select_dtypes(include="object").columns

df[cat_cols] = df[cat_cols].fillna("Unknown")

In [9]:
#Validating NULL values:
missing = df.isnull().sum()
missing_pct = (missing / len(df)) * 100

pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percentage": missing_pct
}).head(15)

                        Missing_Count  Missing_Percentage
Report Number                       0                 0.0
Local Case Number                   0                 0.0
Agency Name                         0                 0.0
ACRS Report Type                    0                 0.0
Crash Date/Time                     0                 0.0
Route Type                          0                 0.0
Road Name                           0                 0.0
Cross-Street Name                   0                 0.0
Collision Type                      0                 0.0
Weather                             0                 0.0
Surface Condition                   0                 0.0
Light                               0                 0.0
Traffic Control                     0                 0.0
Driver Substance Abuse              0                 0.0
Driver At Fault                     0                 0.0

In [10]:
#Replacing the 0 value with Nan:
df["Vehicle Year"] = df["Vehicle Year"].replace(0, np.nan)
df = df.dropna(subset=["Vehicle Year"])

In [12]:
#Fixing date and time column:
df["Crash Date/Time"] = pd.to_datetime(
    df["Crash Date/Time"],
    errors="coerce"
)

df = df.dropna(subset=["Crash Date/Time"])

In [13]:
df.head()

,Report Number,Local Case Number,Agency Name,ACRS Report Type,Crash Date/Time,Route Type,Road Name,Cross-Street Name,Collision Type,Weather,...,Driver Substance Abuse,Driver At Fault,Injury Severity,Driver Distracted By,Drivers License State,Vehicle Body Type,Speed Limit,Vehicle Year,Vehicle Make,Vehicle Model
0,MCP3126006X,250037402,MONTGOMERY,Injury Crash,2025-08-21 17:21:00,Maryland (State) Route,Unknown,Unknown,Front to Rear,Clear,...,"Not Suspect of Alcohol Use, Not Suspect of Dru...",Yes,No Apparent Injury,"Other Action (looking away from task, etc.)",MD,Passenger Car,40,2013.0,KIA,SOUL
2,MCP296500BC,250033157,MONTGOMERY,Property Damage Crash,2025-07-25 11:55:00,Bicycle Route,Unknown,NEW HAMPSHIRE AVE (SB/L) NORBECK RD (WB/L) SPE...,"Sideswipe, Same Direction",Clear,...,"Not Suspect of Alcohol Use, Not Suspect of Dru...",No,No Apparent Injury,Not Distracted,CO,Passenger Car,40,2023.0,LEXUS,RX
3,MCP2159003K,250037509,MONTGOMERY,Property Damage Crash,2025-08-22 10:36:00,Maryland (State) Route,Unknown,Unknown,Front to Rear,Clear,...,"Not Suspect of Alcohol Use, Not Suspect of Dru...",Yes,No Apparent Injury,"Manually Operating (dialing, playing game, etc.)",MD,Van - Passenger (&lt;9 Seats),30,2003.0,TOYOTA,SIENNA
4,MCP312900D6,250034573,MONTGOMERY,Property Damage Crash,2025-08-03 14:10:00,Unknown,Unknown,Unknown,Rear To Side,Clear,...,"Unknown, Unknown",No,Unknown,Unknown,Unknown,Sport Utility Vehicle,0,2023.0,SUBARU,IMPREZA
5,MCP284600BN,250037004,MONTGOMERY,Injury Crash,2025-08-19 09:50:00,County Route,GRAND PRE RD,Unknown,Single Vehicle,Rain,...,"Not Suspect of Alcohol Use, Not Suspect of Dru...",No,No Apparent Injury,Not Distracted,MD,Passenger Car,25,2016.0,MAZDA,CX-5

In [14]:
#Checking for duplicate values:
df.duplicated().sum()

13

In [15]:
#Droping duplicate values:
df = df.drop_duplicates()

In [25]:
df["Crash Hour"] = df["Crash Date/Time"].dt.hour
df["Crash Day"] = df["Crash Date/Time"].dt.day_name()
df["Crash Month"] = df["Crash Date/Time"].dt.month

In [26]:
#Converting texts/objects to proper format:
columns_to_clean = [
    "Injury Severity",
    "Vehicle Body Type",
    "Vehicle Make",
    "Crash Day"
]

for col in columns_to_clean:
    df[col] = (
        df[col].str.strip()
        .str.lower()
        .str.title()
    )

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 203908 entries, 0 to 208967
Data columns (total 26 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Report Number           203908 non-null  object
 1   Local Case Number       203908 non-null  object
 2   Agency Name             203908 non-null  object
 3   ACRS Report Type        203908 non-null  object
 4   Crash Date/Time         203908 non-null  datetime64[ns]
 5   Route Type              203908 non-null  object
 6   Road Name               203908 non-null  object
 7   Cross-Street Name       203908 non-null  object
 8   Collision Type          203908 non-null  object
 9   Weather                 203908 non-null  object
 10  Surface Condition       203908 non-null  object
 11  Light                   203908 non-null  object
 12  Traffic Control         203908 non-null  object
 13  Driver Substance Abuse  203908 non-null  object
 14  Driver At Fault         203908 non-null  object
 15  Injury Severity         203908 non-null  object
 16  Driver Distracted By    203908 non-null  object
 17  Drivers License State   203908 non-null  object
 18  Vehicle Body Type       203908 non-null  object
 19  Speed Limit             203908 non-null  int64
 20  Vehicle Year            203908 non-null  float64
 21  Vehicle Make            203908 non-null  object
 22  Vehicle Model           203908 non-null  object
 23  Crash Hour              203908 non-null  int32
 24  Crash Day               203908 non-null  object
 25  Crash Month             203908 non-null  int32
dtypes: datetime64[ns](1), float64(1), int32(2), int64(1), object(21)
memory usage: 40.4+ MB

In [28]:
#Validating:
df.head()

,Report Number,Local Case Number,Agency Name,ACRS Report Type,Crash Date/Time,Route Type,Road Name,Cross-Street Name,Collision Type,Weather,...,Driver Distracted By,Drivers License State,Vehicle Body Type,Speed Limit,Vehicle Year,Vehicle Make,Vehicle Model,Crash Hour,Crash Day,Crash Month
0,MCP3126006X,250037402,MONTGOMERY,Injury Crash,2025-08-21 17:21:00,Maryland (State) Route,Unknown,Unknown,Front to Rear,Clear,...,"Other Action (looking away from task, etc.)",MD,Passenger Car,40,2013.0,Kia,SOUL,17,Thursday,8
2,MCP296500BC,250033157,MONTGOMERY,Property Damage Crash,2025-07-25 11:55:00,Bicycle Route,Unknown,NEW HAMPSHIRE AVE (SB/L) NORBECK RD (WB/L) SPE...,"Sideswipe, Same Direction",Clear,...,Not Distracted,CO,Passenger Car,40,2023.0,Lexus,RX,11,Friday,7
3,MCP2159003K,250037509,MONTGOMERY,Property Damage Crash,2025-08-22 10:36:00,Maryland (State) Route,Unknown,Unknown,Front to Rear,Clear,...,"Manually Operating (dialing, playing game, etc.)",MD,Van - Passenger (&Lt;9 Seats),30,2003.0,Toyota,SIENNA,10,Friday,8
4,MCP312900D6,250034573,MONTGOMERY,Property Damage Crash,2025-08-03 14:10:00,Unknown,Unknown,Unknown,Rear To Side,Clear,...,Unknown,Unknown,Sport Utility Vehicle,0,2023.0,Subaru,IMPREZA,14,Sunday,8
5,MCP284600BN,250037004,MONTGOMERY,Injury Crash,2025-08-19 09:50:00,County Route,GRAND PRE RD,Unknown,Single Vehicle,Rain,...,Not Distracted,MD,Passenger Car,25,2016.0,Mazda,CX-5,9,Tuesday,8

In [29]:
#Savind the cleaned report in a csv file:
df.to_csv("Crash_Report_Cleaned.csv", index=False)

In [30]:
#Validating:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Duplicate rows:", df.duplicated().sum())
print("Remaining nulls:", df.isnull().sum().sum())

Rows: 203908
Columns: 26
Duplicate rows: 0
Remaining nulls: 0